### ISSUE TITLE
Sorting properties should be displayed in alphabetical order

### ISSUE THREAD

**Issue by jscharf** [ciena-frost/ember-frost-sort#77]
There are new requirements for the `ember-frost-sort`, based on internal discussions with the UX team. They are as follows:

- ~list of sorting properties should be sorted alphabetically~
- list of sorting properties should display selected value in its ~sorted~ original position, rather than at the top of the list

**Comment by notmessenger** [comment]
> list of sorting properties should be sorted alphabetically

I'd prefer to see this implemented via a utility that can be imported from this codebase that can assist with the alphabetization of the data passed to the component but the component itself should not be performing such alphabetization.  The component should display data in the order it was given so that it can support any desired use case rather than only supporting one.  With a utility class it can achieve the same goal while remaining ultimately flexible and usable.

**Comment by jscharf** [comment]
I can definitely see the value in leaving the data as-is and not modifying it. I have removed the alphabetical sorting of the sorting properties from pull request #78.

There is already a `sort` utility that is exported from this add-on, so I could make use of that in the consuming application to sort the sorting properties before passing them to `ember-frost-sort`.

**Comment by notmessenger** [comment]
And we should update the documentation in #78 as well to indicate that this is the approach to take so users are presented with good use cases for common problems they may run into

**Comment by jscharf** [comment]
I have opened issue #79 to track the documentation update.
